- project:
    templates:
      - golang-jobs
    check:
      jobs:
        - golang-lint
        - cni-build-image
    gate:
      jobs:
        - golang-lint
        - cni-build-image
- job:
    name: cni-build-image
    parent: nuage-build-docker-image
    vars:
      zuul_work_dir: "{{ ansible_user_dir }}/src/github.com/{{ zuul.project.name }}"
      container_command: docker
      docker_images:
        - context: .
          dockerfile: Dockerfile
          repository: nuage/cni
          go_task: make
          build_args:
            - "http_proxy={{ proxy_env.http_proxy if proxy_env is defined else '' }}"
            - "https_proxy={{ proxy_env.https_proxy if proxy_env is defined else '' }}"
