# This ConfigMap is used to configure Nuage VSP configuration on master nodes
kind: ConfigMap
apiVersion: v1
metadata:
  name: nuage-master-config
  namespace: kube-system
data:
  # This will generate the required Nuage monitor configuration
  # on master nodes
  monitor_yaml_config: |
      kubeConfig: /etc/kubernetes/kubeconfig

      masterConfig: /var/usr/share/nuagekubemon/net-config.yaml
      # URL of the VSD Architect
      vsdApiUrl: https://xmpp.example.com:7443
      # API version to query against
      vspVersion: v5_0
      # Name of the enterprise in which pods will reside
      enterpriseName: kubernetes
      # Name of the domain in which pods will reside
      domainName: kubernetes
      # VSD generated user certificate file location on master node
      userCertificateFile: /etc/kubernetes/pki/k8s-admin.pem
      # VSD generated user key file location on master node
      userKeyFile: /etc/kubernetes/pki/k8s-admin-Key.pem
      # Location where logs should be saved
      log_dir: /var/log/nuagekubemon
      # Monitor rest server paramters
      # Logging level for the nuage monitor
      # allowed options are: 0 => INFO, 1 => WARNING, 2 => ERROR, 3 => FATAL
      logLevel: 0
      # Parameters related to the nuage monitor REST server
      nuageMonServer:
          URL: 0.0.0.0:9443
          certificateDirectory: /etc/kubernetes/pki
      # etcd config required for HA
      etcdClientConfig:
          ca: ""
          certFile: ""
          keyFile: ""
          urls:
             - http://127.0.0.1:2379
      # auto scale subnets feature
      # 0 => disabled(default) 
      # 1 => enabled
      autoScaleSubnets: 0

  # This will generate the required Nuage network configuration
  # on master nodes
  net_yaml_config: |
      networkConfig:
        clusterNetworkCIDR: 70.70.0.0/16
        serviceNetworkCIDR: 192.168.0.0/16
        hostSubnetLength: 8

---

# This manifest installs Nuage monitor on master nodes in a Tectonic cluster
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: kube-nuage-monitor
  namespace: kube-system
  labels:
    tier: node
    k8s-app: nuage
spec:
  selector:
    matchLabels:
      tier: node
      k8s-app: nuage
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        k8s-app: nuage
    spec:
      containers:
      - name: install-nuage-monitor
        image: nuage/master:v5.2.1
        ports:
          - containerPort: 9443
            hostPort: 9443
        command: ["/configure-master.sh"]
        args: ["k8s", "is_coreos"]
        securityContext:
          privileged: true
        env:
        # Set the hostname based on the k8s node name.
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # nuagekubemon.yaml config to install on each master node.
        - name: NUAGE_MASTER_VSP_CONFIG
          valueFrom:
            configMapKeyRef:
              name: nuage-master-config
              key: monitor_yaml_config
        # net-config.yaml config to install on each master node.
        - name: NUAGE_MASTER_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: nuage-master-config
              key: net_yaml_config
        volumeMounts:
        - name: cni-log-dir
          mountPath: /var/log
        - name: tectonic-var-dir
          mountPath: /host/var
        - name: tectonic-cert-dir
          mountPath: /etc/kubernetes/pki/
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        install-monitor: "true"
      volumes:
        - name: cni-log-dir
          hostPath:
            path: /var/log
        - name: tectonic-var-dir
          hostPath:
            path: /var
        - name: tectonic-cert-dir
          hostPath:
            path: /etc/kubernetes/pki/
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
